/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RealisationsIndexRouteImport } from './routes/realisations.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RealisationsSlugRouteImport } from './routes/realisations.$slug'
import { Route as BlogAssistantRouteImport } from './routes/blog.assistant'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminProjetsRouteImport } from './routes/admin.projets'
import { Route as AdminLeadershipRouteImport } from './routes/admin.leadership'
import { Route as AdminDemandesRouteImport } from './routes/admin.demandes'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as BlogAssistantIndexRouteImport } from './routes/blog.assistant.index'
import { Route as BlogAssistantThreadIdRouteImport } from './routes/blog.assistant.$threadId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsIndexRoute = RealisationsIndexRouteImport.update({
  id: '/realisations/',
  path: '/realisations/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RealisationsSlugRoute = RealisationsSlugRouteImport.update({
  id: '/realisations/$slug',
  path: '/realisations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAssistantRoute = BlogAssistantRouteImport.update({
  id: '/blog/assistant',
  path: '/blog/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjetsRoute = AdminProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadershipRoute = AdminLeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDemandesRoute = AdminDemandesRouteImport.update({
  id: '/demandes',
  path: '/demandes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogAssistantIndexRoute = BlogAssistantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogAssistantRoute,
} as any)
const BlogAssistantThreadIdRoute = BlogAssistantThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => BlogAssistantRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/profil': typeof ProfilRoute
  '/services': typeof ServicesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/demandes': typeof AdminDemandesRoute
  '/admin/leadership': typeof AdminLeadershipRoute
  '/admin/projets': typeof AdminProjetsRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/assistant': typeof BlogAssistantRouteWithChildren
  '/realisations/$slug': typeof RealisationsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/realisations/': typeof RealisationsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/blog/assistant/$threadId': typeof BlogAssistantThreadIdRoute
  '/blog/assistant/': typeof BlogAssistantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/profil': typeof ProfilRoute
  '/services': typeof ServicesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/demandes': typeof AdminDemandesRoute
  '/admin/leadership': typeof AdminLeadershipRoute
  '/admin/projets': typeof AdminProjetsRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/realisations/$slug': typeof RealisationsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/realisations': typeof RealisationsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/blog/assistant/$threadId': typeof BlogAssistantThreadIdRoute
  '/blog/assistant': typeof BlogAssistantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/profil': typeof ProfilRoute
  '/services': typeof ServicesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/demandes': typeof AdminDemandesRoute
  '/admin/leadership': typeof AdminLeadershipRoute
  '/admin/projets': typeof AdminProjetsRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/assistant': typeof BlogAssistantRouteWithChildren
  '/realisations/$slug': typeof RealisationsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/realisations/': typeof RealisationsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/blog/assistant/$threadId': typeof BlogAssistantThreadIdRoute
  '/blog/assistant/': typeof BlogAssistantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/mcp'
    | '/profil'
    | '/services'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/articles'
    | '/admin/demandes'
    | '/admin/leadership'
    | '/admin/projets'
    | '/api/chat'
    | '/blog/$slug'
    | '/blog/assistant'
    | '/realisations/$slug'
    | '/admin/'
    | '/blog/'
    | '/realisations/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/blog/assistant/$threadId'
    | '/blog/assistant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/contact'
    | '/mcp'
    | '/profil'
    | '/services'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/articles'
    | '/admin/demandes'
    | '/admin/leadership'
    | '/admin/projets'
    | '/api/chat'
    | '/blog/$slug'
    | '/realisations/$slug'
    | '/admin'
    | '/blog'
    | '/realisations'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/blog/assistant/$threadId'
    | '/blog/assistant'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/mcp'
    | '/profil'
    | '/services'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/articles'
    | '/admin/demandes'
    | '/admin/leadership'
    | '/admin/projets'
    | '/api/chat'
    | '/blog/$slug'
    | '/blog/assistant'
    | '/realisations/$slug'
    | '/admin/'
    | '/blog/'
    | '/realisations/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/blog/assistant/$threadId'
    | '/blog/assistant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  McpRoute: typeof McpRoute
  ProfilRoute: typeof ProfilRoute
  ServicesRoute: typeof ServicesRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogAssistantRoute: typeof BlogAssistantRouteWithChildren
  RealisationsSlugRoute: typeof RealisationsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  RealisationsIndexRoute: typeof RealisationsIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations/': {
      id: '/realisations/'
      path: '/realisations'
      fullPath: '/realisations/'
      preLoaderRoute: typeof RealisationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/realisations/$slug': {
      id: '/realisations/$slug'
      path: '/realisations/$slug'
      fullPath: '/realisations/$slug'
      preLoaderRoute: typeof RealisationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/assistant': {
      id: '/blog/assistant'
      path: '/blog/assistant'
      fullPath: '/blog/assistant'
      preLoaderRoute: typeof BlogAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projets': {
      id: '/admin/projets'
      path: '/projets'
      fullPath: '/admin/projets'
      preLoaderRoute: typeof AdminProjetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leadership': {
      id: '/admin/leadership'
      path: '/leadership'
      fullPath: '/admin/leadership'
      preLoaderRoute: typeof AdminLeadershipRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/demandes': {
      id: '/admin/demandes'
      path: '/demandes'
      fullPath: '/admin/demandes'
      preLoaderRoute: typeof AdminDemandesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/assistant/': {
      id: '/blog/assistant/'
      path: '/'
      fullPath: '/blog/assistant/'
      preLoaderRoute: typeof BlogAssistantIndexRouteImport
      parentRoute: typeof BlogAssistantRoute
    }
    '/blog/assistant/$threadId': {
      id: '/blog/assistant/$threadId'
      path: '/$threadId'
      fullPath: '/blog/assistant/$threadId'
      preLoaderRoute: typeof BlogAssistantThreadIdRouteImport
      parentRoute: typeof BlogAssistantRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminDemandesRoute: typeof AdminDemandesRoute
  AdminLeadershipRoute: typeof AdminLeadershipRoute
  AdminProjetsRoute: typeof AdminProjetsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArticlesRoute: AdminArticlesRoute,
  AdminDemandesRoute: AdminDemandesRoute,
  AdminLeadershipRoute: AdminLeadershipRoute,
  AdminProjetsRoute: AdminProjetsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogAssistantRouteChildren {
  BlogAssistantThreadIdRoute: typeof BlogAssistantThreadIdRoute
  BlogAssistantIndexRoute: typeof BlogAssistantIndexRoute
}

const BlogAssistantRouteChildren: BlogAssistantRouteChildren = {
  BlogAssistantThreadIdRoute: BlogAssistantThreadIdRoute,
  BlogAssistantIndexRoute: BlogAssistantIndexRoute,
}

const BlogAssistantRouteWithChildren = BlogAssistantRoute._addFileChildren(
  BlogAssistantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  McpRoute: McpRoute,
  ProfilRoute: ProfilRoute,
  ServicesRoute: ServicesRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogAssistantRoute: BlogAssistantRouteWithChildren,
  RealisationsSlugRoute: RealisationsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  RealisationsIndexRoute: RealisationsIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
