/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RealisationsIndexRouteImport } from './routes/realisations.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RealisationsSlugRouteImport } from './routes/realisations.$slug'
import { Route as BlogAssistantRouteImport } from './routes/blog.assistant'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminProjetsRouteImport } from './routes/admin.projets'
import { Route as AdminDemandesRouteImport } from './routes/admin.demandes'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'
import { Route as BlogAssistantIndexRouteImport } from './routes/blog.assistant.index'
import { Route as BlogAssistantThreadIdRouteImport } from './routes/blog.assistant.$threadId'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsIndexRoute = RealisationsIndexRouteImport.update({
  id: '/realisations/',
  path: '/realisations/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RealisationsSlugRoute = RealisationsSlugRouteImport.update({
  id: '/realisations/$slug',
  path: '/realisations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAssistantRoute = BlogAssistantRouteImport.update({
  id: '/blog/assistant',
  path: '/blog/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjetsRoute = AdminProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDemandesRoute = AdminDemandesRouteImport.update({
  id: '/demandes',
  path: '/demandes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)
const BlogAssistantIndexRoute = BlogAssistantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogAssistantRoute,
} as any)
const BlogAssistantThreadIdRoute = BlogAssistantThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => BlogAssistantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/profil': typeof ProfilRoute
  '/services': typeof ServicesRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/demandes': typeof AdminDemandesRoute
  '/admin/projets': typeof AdminProjetsRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/assistant': typeof BlogAssistantRouteWithChildren
  '/realisations/$slug': typeof RealisationsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/realisations/': typeof RealisationsIndexRoute
  '/blog/assistant/$threadId': typeof BlogAssistantThreadIdRoute
  '/blog/assistant/': typeof BlogAssistantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/profil': typeof ProfilRoute
  '/services': typeof ServicesRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/demandes': typeof AdminDemandesRoute
  '/admin/projets': typeof AdminProjetsRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/realisations/$slug': typeof RealisationsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/realisations': typeof RealisationsIndexRoute
  '/blog/assistant/$threadId': typeof BlogAssistantThreadIdRoute
  '/blog/assistant': typeof BlogAssistantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/profil': typeof ProfilRoute
  '/services': typeof ServicesRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/demandes': typeof AdminDemandesRoute
  '/admin/projets': typeof AdminProjetsRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/assistant': typeof BlogAssistantRouteWithChildren
  '/realisations/$slug': typeof RealisationsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/realisations/': typeof RealisationsIndexRoute
  '/blog/assistant/$threadId': typeof BlogAssistantThreadIdRoute
  '/blog/assistant/': typeof BlogAssistantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/profil'
    | '/services'
    | '/admin/articles'
    | '/admin/demandes'
    | '/admin/projets'
    | '/api/chat'
    | '/blog/$slug'
    | '/blog/assistant'
    | '/realisations/$slug'
    | '/admin/'
    | '/blog/'
    | '/realisations/'
    | '/blog/assistant/$threadId'
    | '/blog/assistant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/contact'
    | '/profil'
    | '/services'
    | '/admin/articles'
    | '/admin/demandes'
    | '/admin/projets'
    | '/api/chat'
    | '/blog/$slug'
    | '/realisations/$slug'
    | '/admin'
    | '/blog'
    | '/realisations'
    | '/blog/assistant/$threadId'
    | '/blog/assistant'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/profil'
    | '/services'
    | '/admin/articles'
    | '/admin/demandes'
    | '/admin/projets'
    | '/api/chat'
    | '/blog/$slug'
    | '/blog/assistant'
    | '/realisations/$slug'
    | '/admin/'
    | '/blog/'
    | '/realisations/'
    | '/blog/assistant/$threadId'
    | '/blog/assistant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ProfilRoute: typeof ProfilRoute
  ServicesRoute: typeof ServicesRoute
  ApiChatRoute: typeof ApiChatRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogAssistantRoute: typeof BlogAssistantRouteWithChildren
  RealisationsSlugRoute: typeof RealisationsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  RealisationsIndexRoute: typeof RealisationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations/': {
      id: '/realisations/'
      path: '/realisations'
      fullPath: '/realisations/'
      preLoaderRoute: typeof RealisationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/realisations/$slug': {
      id: '/realisations/$slug'
      path: '/realisations/$slug'
      fullPath: '/realisations/$slug'
      preLoaderRoute: typeof RealisationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/assistant': {
      id: '/blog/assistant'
      path: '/blog/assistant'
      fullPath: '/blog/assistant'
      preLoaderRoute: typeof BlogAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projets': {
      id: '/admin/projets'
      path: '/projets'
      fullPath: '/admin/projets'
      preLoaderRoute: typeof AdminProjetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/demandes': {
      id: '/admin/demandes'
      path: '/demandes'
      fullPath: '/admin/demandes'
      preLoaderRoute: typeof AdminDemandesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/assistant/': {
      id: '/blog/assistant/'
      path: '/'
      fullPath: '/blog/assistant/'
      preLoaderRoute: typeof BlogAssistantIndexRouteImport
      parentRoute: typeof BlogAssistantRoute
    }
    '/blog/assistant/$threadId': {
      id: '/blog/assistant/$threadId'
      path: '/$threadId'
      fullPath: '/blog/assistant/$threadId'
      preLoaderRoute: typeof BlogAssistantThreadIdRouteImport
      parentRoute: typeof BlogAssistantRoute
    }
  }
}

interface AdminRouteChildren {
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminDemandesRoute: typeof AdminDemandesRoute
  AdminProjetsRoute: typeof AdminProjetsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArticlesRoute: AdminArticlesRoute,
  AdminDemandesRoute: AdminDemandesRoute,
  AdminProjetsRoute: AdminProjetsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogAssistantRouteChildren {
  BlogAssistantThreadIdRoute: typeof BlogAssistantThreadIdRoute
  BlogAssistantIndexRoute: typeof BlogAssistantIndexRoute
}

const BlogAssistantRouteChildren: BlogAssistantRouteChildren = {
  BlogAssistantThreadIdRoute: BlogAssistantThreadIdRoute,
  BlogAssistantIndexRoute: BlogAssistantIndexRoute,
}

const BlogAssistantRouteWithChildren = BlogAssistantRoute._addFileChildren(
  BlogAssistantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ProfilRoute: ProfilRoute,
  ServicesRoute: ServicesRoute,
  ApiChatRoute: ApiChatRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogAssistantRoute: BlogAssistantRouteWithChildren,
  RealisationsSlugRoute: RealisationsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  RealisationsIndexRoute: RealisationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
